import argparse

args = argparse.ArgumentParser()
args.add_argument('--dataset', type=str, default='ICEWS14')
args.add_argument('--batch_size', type=int, default=1000)
args.add_argument('--emb_size', type=int, default=500)
args.add_argument('--max_epochs', type=int, default=5)
args.add_argument('--init', type=float, default=1e-3)
args.add_argument('--lr', type=float, default=1e-1)
args.add_argument('--gpu', type=int, default=0)
args.add_argument('--max_sample', type=int, default=5)
args.add_argument('--seq_len', type=int, default=128)
args.add_argument('--m', type=str, default='train')
args.add_argument('--epoch', type=int, default=0)
args.add_argument('--mi', type=int, default=0)
args.add_argument('--entity_epoch', type=int, default=1)
args.add_argument('--rel_epoch', type=int, default=1)
args.add_argument('--start_epoch', type=int, default=0)
args.add_argument('--test_sample', type=int, default=1)
args.add_argument('--rand_flag', type=bool, default=False)
args.add_argument('--pre_epochs', type=int, default=5)
args.add_argument('--finetune_epochs', type=int, default=5)
args.add_argument('--seed', type=int, default=0)
args.add_argument('--second', type=bool, default=False)
args = args.parse_args()
